-- CreateEnum
CREATE TYPE "ExpenseCategoryGroup" AS ENUM ('ADMINISTRATIVE', 'MOBILITY', 'MARKETING', 'IT', 'OPERATIONS', 'LEGAL', 'OTHER');

-- CreateEnum
CREATE TYPE "ExpenseCategory" AS ENUM ('OFFICE_RENT', 'OFFICE_CHARGES', 'INTERNET', 'OFFICE_SUPPLIES', 'SOFTWARE_SUBSCRIPTIONS', 'POSTAL_FEES', 'INSURANCE', 'LOCAL_TRANSPORT', 'MILEAGE_REIMBURSEMENT', 'FLIGHTS', 'ACCOMMODATION', 'PER_DIEM', 'CAR_RENTAL', 'MISSION_FEES', 'ONLINE_ADS', 'DESIGN', 'PRINTING', 'PHOTOGRAPHY', 'SOCIAL_MEDIA', 'PARTNERSHIPS', 'WEBSITE', 'SOFTWARE_DEV', 'SERVER_HOSTING', 'CYBERSECURITY', 'HARDWARE_PURCHASE', 'SOFTWARE_LICENSES', 'TECH_EQUIPMENT', 'BANK_FEES', 'FREELANCE_FEES', 'EXTERNAL_MISSIONS', 'CERTIFICATION_FEES', 'LEGAL_FEES', 'ADMIN_REGISTRATION', 'LICENSE_RENEWAL', 'COMPLIANCE_FEES', 'TAXES', 'PENALTIES', 'DONATIONS', 'LOSSES', 'ONE_TIME_PURCHASE');

-- CreateTable
CREATE TABLE "Expense" (
    "id" TEXT NOT NULL,
    "amount" DOUBLE PRECISION NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "category" "ExpenseCategory" NOT NULL,
    "group" "ExpenseCategoryGroup" NOT NULL,
    "description" TEXT,
    "fileUrl" TEXT,
    "employeeId" TEXT,
    "projectId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Expense_pkey" PRIMARY KEY ("id")
);
