/* eslint-disable no-unused-vars */
export enum ExpenseCategory {
  // ADMINISTRATIVE
  OFFICE_RENT = 'OFFICE_RENT',
  OFFICE_CHARGES = 'OFFICE_CHARGES',
  INTERNET = 'INTERNET',
  OFFICE_SUPPLIES = 'OFFICE_SUPPLIES',
  SOFTWARE_SUBSCRIPTIONS = 'SOFTWARE_SUBSCRIPTIONS',
  POSTAL_FEES = 'POSTAL_FEES',
  INSURANCE = 'INSURANCE',

  // MOBILITY
  LOCAL_TRANSPORT = 'LOCAL_TRANSPORT',
  MILEAGE_REIMBURSEMENT = 'MILEAGE_REIMBURSEMENT',
  FLIGHTS = 'FLIGHTS',
  ACCOMMODATION = 'ACCOMMODATION',
  PER_DIEM = 'PER_DIEM',
  CAR_RENTAL = 'CAR_RENTAL',
  MISSION_FEES = 'MISSION_FEES',

  // MARKETING
  ONLINE_ADS = 'ONLINE_ADS',
  DESIGN = 'DESIGN',
  PRINTING = 'PRINTING',
  PHOTOGRAPHY = 'PHOTOGRAPHY',
  SOCIAL_MEDIA = 'SOCIAL_MEDIA',
  PARTNERSHIPS = 'PARTNERSHIPS',
  WEBSITE = 'WEBSITE',

  // IT
  SOFTWARE_DEV = 'SOFTWARE_DEV',
  SERVER_HOSTING = 'SERVER_HOSTING',
  CYBERSECURITY = 'CYBERSECURITY',
  HARDWARE_PURCHASE = 'HARDWARE_PURCHASE',
  SOFTWARE_LICENSES = 'SOFTWARE_LICENSES',

  // OPERATIONS
  TECH_EQUIPMENT = 'TECH_EQUIPMENT',
  BANK_FEES = 'BANK_FEES',
  FREELANCE_FEES = 'FREELANCE_FEES',
  EXTERNAL_MISSIONS = 'EXTERNAL_MISSIONS',
  CERTIFICATION_FEES = 'CERTIFICATION_FEES',

  // LEGAL
  LEGAL_FEES = 'LEGAL_FEES',
  ADMIN_REGISTRATION = 'ADMIN_REGISTRATION',
  LICENSE_RENEWAL = 'LICENSE_RENEWAL',
  COMPLIANCE_FEES = 'COMPLIANCE_FEES',

  // OTHER
  TAXES = 'TAXES',
  PENALTIES = 'PENALTIES',
  DONATIONS = 'DONATIONS',
  LOSSES = 'LOSSES',
  ONE_TIME_PURCHASE = 'ONE_TIME_PURCHASE',
}
